### ISSUE TITLE
Issue with Simulation Initialization

### ISSUE THREAD

**Issue by mmcza** [arplaboratory/RotorTM#10]
Hi, I'm trying to run the simulator but I came with some errors in the console.

![Screenshot from 2024-05-14 13-04-51](https://github.com/arplaboratory/RotorTM/assets/46852756/144c9a0d-2382-4ecd-92fd-6f394adc1cbc)

Parameters from summary:

```
SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.15

NODES
  /
    controller_1 (rotor_tm_control/controller_node.py)
    controller_2 (rotor_tm_control/controller_node.py)
    controller_3 (rotor_tm_control/controller_node.py)
    rviz (rviz/rviz)
    sim (rotor_tm/runsim.py)
    traj (rotor_tm_traj/traj_node.py)

ROS_MASTER_URI=http://localhost:11311

process[sim-1]: started with pid [5709]
process[traj-2]: started with pid [5710]
process[controller_1-3]: started with pid [5711]
process[controller_2-4]: started with pid [5712]
process[controller_3-5]: started with pid [5713]
```

### The lines of code that the issue is about:

https://github.com/arplaboratory/RotorTM/blob/069bddfd9424627b50bf2aaa0508fa673965df36/rotor_tm_control/src/rotor_tm_control/controller.py#L294C1-L300C49 - 2 returns in a function - probably an issue with commits

https://github.com/arplaboratory/RotorTM/blob/069bddfd9424627b50bf2aaa0508fa673965df36/rotor_tm_sim/src/rotor_tm_sim/simulation_base.py#L11 - library that causes a problem during launching the simulation (I thought that it's not used anywhere so I commented the line and it removed the warning and now the error looks like this:
![image](https://github.com/arplaboratory/RotorTM/assets/46852756/1173be56-7f40-4715-b04c-ab034fd3ed92)

**Comment by lguanrui** [comment]
Hi! Sorry for the late reply! I have resolved the bugs that you have reported. Can you kindly try the latest update and let me know what problems you have? In case you didn't hear me back, please send an email to lguanrui@nyu.edu to remind me to come back to visit this issue! Thank you!

**Comment by lguanrui** [comment]
closing this because of inactive response.
